### ISSUE TITLE
Province-only map?

### ISSUE THREAD

**Issue by shreyans-tamang** [Acesmndr/nepal-geojson#14]
Hi, would you add one more static map in your folder which has province only?
I see that there is a way to install and generate it myself but I'm not really sure how to.
Thanks. Great work, btw.

**Comment by Acesmndr** [comment]
@shreyans-tamang The easiest way would be to install it globally via CLI as described in the Readme file.

```shell
npm i -g nepal-geojson
# to get the geojson of province 1 use the command below
nepal-geojson province 1
```

or if you don't want to install the library you could run it using npx

```
npx nepal-geojson province 2
```

P.S. Extremely sorry for the really late reply. This issue notification got buried in a pile of notifications. Also thanks for the appreciation. :)

**Comment by shreyans-tamang** [comment]
THanks!
